### ISSUE TITLE
DecoderException

### ISSUE THREAD

**Issue by Swedz** [WaterfallMC/Travertine#62]
When I send a message from the server to the player (spigot):
```
staff.sendMessage(PREFIX + player.getName() + " has been detected for " + cheat.getName() + " (" + detection.getLabel() + ") [" + data + "]");
```

Where PREFIX is just:

```
public static final String PREFIX = ChatColor.DARK_RED + "[Hydra]: " + ChatColor.GRAY;
```

None of these values are null, and the error is completely BungeeCord/Travertine side.

I get this error in Travertine (bungee) console:

```
io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents:
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:69) ~[Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 400))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403) ~[Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108) ~[Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98) ~[Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:40) ~[Travertine.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:c57c062:34]
        ... 27 more
```

**Comment by electronicboy** [comment]
Your server had sent an empty packet, bungeecord saw it and threw the above error
