### ISSUE TITLE
Players getting kicked by talking.

### ISSUE THREAD

**Issue by SantyPlays** [WaterfallMC/Travertine#65]
[23:39:18 ERROR]: [/200.126.167.233:22822|SantyPlays] <-> DownstreamBridge <-> [survival] - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents:

        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:69) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 128))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:40) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        ... 23 more

**Comment by SantyPlays** [comment]
Another kick message.


[23:10:48 ERROR]: [/190.76.250.146:7859|ValerynR] <-> DownstreamBridge <-> [survival] - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents:

        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:69) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 1, widx: 1, cap: 112))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:40) ~[custom.jar:git:Travertine-Bootstrap:1.12-SNAPSHOT:e095deb:39]
        ... 23 more

**Comment by electronicboy** [comment]
looking back at this, the cause is clear; Your server apparently sent an empty packet, and so when it tried to read the packet ID to see what is going on, it threw the above error
